---

nix_commands:
  - "nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager"
  - "nix-channel --update"
  - "nix-shell '<home-manager>' -A install"
  - "home-manager -f ~/.config/nixpkgs/hoss.nix switch"
