
# zpool create z2 raidz2 -m /mnt/z2 -o ashift=12 /dev/disk/by-id/ata-HGST_HDN728080ALE604_VJH35HDX /dev/disk/by-id/ata-HGST_HUH728080ALE600_VKGKGEVX /dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7SGRVHYC /dev/disk/by-id/ata-WDC_WD80EZZX-11CSGA0_VK0U9B3Y

# # zfs raidz2
# ## in use
# /dev/disk/by-id/ata-HGST_HDN728080ALE604_VJH35HDX
# /dev/disk/by-id/ata-HGST_HUH728080ALE600_VKGKGEVX
# /dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7SGRVHYC
# /dev/disk/by-id/ata-WDC_WD80EZZX-11CSGA0_VK0U9B3Y
# ## spare
# /dev/disk/by-id/ata-ST8000AS0002-1NA17Z_Z8411V1G

main_username: alex

# geerlingguy.ntp
ntp_timezone: "Europe/London"

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
  - { alias: "dcporph", command: "docker-compose -f ~/docker-compose.yml --remove-orphans " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }
  - { alias: "appdata", command: "cd /mnt/z2/pennywise/appdata" }
  - { alias: "zspace", command: "zfs list -o space" }
  - { alias: "zsnap", command: "zfs list -o space | sort -k4 --human-numeric-sort" }
  - { alias: "dfclean", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs | sort -k 6" }
  - { alias: "hdtemp", command: "sudo hddtemp -q /dev/sd[a,b,c,d,e,f,g,h,i,j,k,l,m,n]" }
  - { alias: "nvmetemp", command: "for i in {0..3}; do nvme smart-log /dev/nvme'$i'n1 | grep temperature; done;" } 

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: fio
  - name: git
  - name: hddtemp
  - name: htop
  - name: ffmpeg
  - name: iftop
  - name: intel-gpu-tools
  - name: iotop
  - name: ipmitool
  - name: lm-sensors
  - name: mc
  - name: mutt
  - name: ncdu
  - name: net-tools
  - name: nfs-kernel-server
  - name: nmap
  - name: nvme-cli
  - name: openssh-server
  - name: python3
  - name: python-setuptools
  #- name: qemu-guest-agent
  #- name: sanoid
  - name: screen
  #- name: ssh-import-id
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  #- name: wireguard-tools
  - name: xfsprogs
  - name: zfsutils-linux

# ktz-sanoid
syncoid_cron_jobs: []

# ktz-traefik
traefik_file_provider: false

# ironicbadger.docker_compose_generator
appdata_path: /mnt/z2/pennywise/appdata
local_domain: "p.nr.{{ domain_me }}"
containers:
  ###
  - service_name: tr
    active: true
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    extra_hosts:
      - host.docker.internal:172.17.0.1
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    volumes:
      - "{{ appdata_path }}/traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
  ###
  - service_name: homer
    active: true
    image: b4bz/homer
    labels:
      - traefik.enable=true
      - "traefik.http.routers.homer.rule=Host(`home.{{ local_domain }}`)"
      - traefik.http.routers.homer.tls.certresolver=cloudflare
      #- traefik.http.services.homer.loadbalancer.server.port=80
    volumes:
      - "{{ appdata_path }}/homer:/www/assets"
    restart: unless-stopped
  ###
  - service_name: plex
    active: true
    image: plexinc/pms-docker
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - "traefik.http.routers.plex.rule=Host(`plex.{{ local_domain }}`)"
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400
    volumes:
      - "{{ appdata_path }}/plex/config:/config"
      - /mnt/z2/tv/recordings:/data
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: librespeed
    active: true
    image: linuxserver/librespeed
    ports:
      - 8008:80
    labels:
      - traefik.enable=true
      - "traefik.http.routers.librespeed.rule=Host(`speedtest.{{ local_domain }}`)"
      - traefik.http.routers.librespeed.tls.certresolver=cloudflare
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - "PASSWORD={{ librespeed_password }}"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: smokeping
    active: true
    image: linuxserver/smokeping
    volumes:
      - "{{ appdata_path }}/smokeping/config:/config"
      - "{{ appdata_path }}/smokeping/data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.{{ local_domain }}`)"
      - traefik.http.routers.smokeping.tls.certresolver=cloudflare
      - traefik.http.services.smokeping.loadbalancer.server.port=80
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: bookstack
    active: true
    image: linuxserver/bookstack
    depends_on:
      - bookstack_db
    labels:
      - traefik.enable=true
      - "traefik.http.routers.bookstack.rule=Host(`wiki.{{ local_domain }}`)"
      - traefik.http.routers.bookstack.tls.certresolver=cloudflare
    ports:
      - 6875:80
    environment:
      - "APP_URL=https://wiki.{{ local_domain }}"
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - "DB_PASS={{ container_mysql_root_password }}"
      - DB_DATABASE=bookstackapp
    volumes:
      - "{{ appdata_path }}/bookstack/config:/config"
    include_global_env_vars: true
    restart: unless-stopped
  - service_name: bookstack_db
    active: true
    image: linuxserver/mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD={{ container_mysql_root_password }}"
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - "MYSQL_PASSWORD={{ container_mysql_root_password }}"
    volumes:
      - "{{ appdata_path }}/bookstack/db:/config"
    include_global_env_vars: true
    restart: unless-stopped
