[terminal.shell]
program = "zsh"

[font]
size = 14

[font.normal]
family = "MesloLGS NF"

[window]
opacity = 1
# decorations = "none"
option_as_alt = "Both"
# decorations_theme_variant = "light"

[scrolling]
history = 15000

# https://github.com/alacritty/alacritty-theme/blob/master/themes/ashes_light.toml
# # https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_material_hard_light.toml

# [keyboard]
# bindings = [{ key = "A", mods = "Alt", chars = "\u001Ba" }]
