- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/statping/"
    state: directory
    # owner: "{{ main_uid }}" # idiotic container writing means that this
    # group: "{{ main_gid }}" # dir must be owned by ROOT *sigh*

- name: install statping config file
  template:
    src: config.yml.j2
    dest: "{{ appdata_path }}/statping/config.yml"