keys:
  # Admins
  - &admins
    - &mjmaurer B3BA2EB7DD7FD95682FB2123470DDCD84F727EEE
  # Machines
  - &machines
    - &smac age19rf3p8aa4g4deyp3tpcujtf4hcd7x3aqdm3ppnnju45fx0wwupqqgvs45f
    - &aspen age17pf8qd9zefu470e8q2sa23w4ws8k7wgth5rdc2ejsn3462ae9fusuul83c
    - &maple age1y7pgjrvg4ezk0ykx56ruxh5tat9gywr4juya78ztnunrcc4z8evseuq5v8

creation_rules:
  # --------------------------------- Common --------------------------------- #
  - path_regex: system/modules/sops/secrets/common.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *aspen
          - *smac
          - *maple
  # Daily Drivers
  - path_regex: system/modules/sops/secrets/common-pc.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *aspen
          - *smac
  # --------------------------------- Machines --------------------------------- #
  - path_regex: system/machines/maple/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *maple