keys:
  # Admins
  - &admins
    - &mjmaurer B3BA2EB7DD7FD95682FB2123470DDCD84F727EEE
  # Machines
  - &machines
    - &aspen age17pf8qd9zefu470e8q2sa23w4ws8k7wgth5rdc2ejsn3462ae9fusuul83c
    - &smac age19rf3p8aa4g4deyp3tpcujtf4hcd7x3aqdm3ppnnju45fx0wwupqqgvs45f


creation_rules:
  - path_regex: system/modules/sops/secrets/common.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *aspen
          - *smac