keys:
  # Admins
  - &admins
    - &mjmaurer 12FCCDCC759F2395C495D154702DC991871434E7
  # Machines
  - &machines
    - &aspen age17pf8qd9zefu470e8q2sa23w4ws8k7wgth5rdc2ejsn3462ae9fusuul83c

creation_rules:
  - path_regex: system/modules/sops/secrets/common.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *aspen