keys:
  # Admins
  - &admins
    - &mjmaurer B3BA2EB7DD7FD95682FB2123470DDCD84F727EEE
  # Machines
  - &machines
    - &smac age19rf3p8aa4g4deyp3tpcujtf4hcd7x3aqdm3ppnnju45fx0wwupqqgvs45f
    - &aspen age17pf8qd9zefu470e8q2sa23w4ws8k7wgth5rdc2ejsn3462ae9fusuul83c
    - &maple age1vgdqnptd3zawh6yew778m0z36y7e7jllygc83wrezq6calsxqg0qhun5t3
    - &willow age1mya8weyrutxpszdd992xtepfrt9zvz0dumzmxvtuja7gnrwwgglsqxwmdk
    - &dove age1a2xfudr0e7gxvlr7gql0p5yzr746dx0ujd8npwvstu25quhe94pqpms5nz
    - &bluejay age1pgy8338p85v09rdycev3lekpf7ugat0n96q35x2jt6s60sxap3gsfzvjpm
    - &ash age18dju7s0yfrt3cexjexjqdhzr6y5vrngu2kq6yq65plm7a59w4qdsmh2ud2
  # Host Groups
  # NOTE: Should match the tags defined in `mylib.nix` and set in `flake.nix` for each machine.
  # `Ad-hoc` means the secret isn't enabled by default based on tags. 
  # NOTE: Remember to run 'sops updatekeys <yaml_path>' after modifying these groups.
  - &full-clients
    - *smac
    - *aspen
  - &dev-clients
    - *smac
    - *aspen  
    - *willow
    - *ash
  - &linux-hosts
    - *maple
    - *willow
    - *dove
    - *bluejay
    - *ash
  - &nas-access
    - *ash
  - &cloudflare
    - *maple
    - *bluejay
    - *dove
  - &garage
    - *maple
  - &duplicacy
    - *willow
    - *maple
  - &postgresql
    - *maple

creation_rules:
  # --------------------------------- Notes --------------------------------- #
  - path_regex: lib/troubleshooting.md$
    key_groups:
      - pgp:
          - *mjmaurer
  # --------------------------------- Common --------------------------------- #
  - path_regex: system/modules/sops/vault/nixos-host.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *linux-hosts
  - path_regex: system/modules/sops/vault/gpg.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *full-clients
  - path_regex: system/modules/sops/vault/smb.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *dev-clients
        merge:
          - age: *nas-access
  - path_regex: system/modules/sops/vault/cloudflare.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *cloudflare
  - path_regex: system/modules/sops/vault/garage.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *garage
  - path_regex: system/modules/sops/vault/postgresql.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *postgresql
  - path_regex: system/modules/duplicacy/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *duplicacy
  # ==== AI ====
  - path_regex: system/modules/sops/vault/ai/openrouter.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *dev-clients
  - path_regex: system/modules/sops/vault/ai/gemini.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *dev-clients
  - path_regex: system/modules/sops/vault/ai/cerebras.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *full-clients
  - path_regex: system/modules/sops/vault/ai/openai.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *full-clients
  - path_regex: system/modules/sops/vault/ai/other.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *full-clients
  # --------------------------- Specific Services ----------------------------- #
  # ==== Common ====

  # ==== Module/App Specific ====
  - path_regex: system/modules/sops/vault/yt-upload.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age: *full-clients
  # --------------------------------- Machines --------------------------------- #
  - path_regex: system/machines/maple/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *maple
  - path_regex: system/machines/willow/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *willow
  - path_regex: system/machines/dove/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *dove
  - path_regex: system/machines/bluejay/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *bluejay
  - path_regex: system/machines/ash/secrets.yaml$
    key_groups:
      - pgp:
          - *mjmaurer
        age:
          - *ash
