---
- hosts: earth
  connection: local
  vars_files:
    - "vault/vault.yaml"
    # - 'group_vars/earth.yaml'
  roles:
    - role: nix-symlink
    - role: danielrolls.nix
    - role: artis3n.tailscale
    - role: geerlingguy.docker
- hosts: bobby
  connection: local
  vars_files:
    - "vault/vault.yaml"
  roles:
    - role: nix-symlink
    - role: danielrolls.nix
    - role: artis3n.tailscale
    - role: geerlingguy.docker
    - role: samba-client
- hosts: proxy
  connection: local
  vars_files:
    - "vault/vault.yaml"
  roles:
    - role: nix-symlink
    - role: danielrolls.nix
    - role: artis3n.tailscale
    - role: geerlingguy.docker
