# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
#enable-normalization-flatten-containers = false
#enable-normalization-opposite-orientation-for-nested-containers = false

start-at-login = true
# The 'accordion-padding' specifies the size of accordion padding
# accordion is the default mode for default workspace 1. Not sure why.
accordion-padding = 0

# I'm not sure why workspace 1 is accordion even though this is the default: 
default-root-container-layout = 'accordion'
default-root-container-orientation = "vertical"

on-focus-changed = [
    # 'exec-and-forget $HOME/.local/bin/tmux-match-focus-vscode.sh',
    'move-mouse window-lazy-center',
]

[exec.env-vars]
PATH = '/opt/homebrew/bin/:${HOME}/.nix-profile/bin:${PATH}'

# ---------------------------------- NOTE ---------------------------------- 
# Currently can't do composition without exec-and-forget which adds delay:
# https://github.com/nikitabobko/AeroSpace/issues/278
# ---------------------------------- NOTE ---------------------------------- 
# For what it's worth, the easiest way to test movement is to open terminal and run aerospace commands to move it around

[mode.main.binding]

alt-shift-c = 'reload-config'
alt-shift-q = 'flatten-workspace-tree'
alt-shift-f = 'fullscreen'

alt-shift-h = 'focus left'
alt-shift-j = 'focus --ignore-floating --boundaries-action wrap-around-the-workspace down'
alt-shift-k = 'focus --ignore-floating --boundaries-action wrap-around-the-workspace up'
alt-shift-l = 'focus right'

# See workspaces_extra mode for additional workspace switching bindings
# alt-t = ['workspace terminal --auto-back-and-forth']
alt-e = 'workspace code --auto-back-and-forth'
alt-w = 'workspace web --auto-back-and-forth'
alt-g = 'workspace llm --auto-back-and-forth'
alt-r = 'workspace notes --auto-back-and-forth'
alt-z = 'workspace zoom --auto-back-and-forth'

# alt-shift-t = 'move-node-to-workspace terminal'
alt-shift-e = [
    'layout floating',
    'move-node-to-workspace --focus-follows-window code',
    'layout tiling',
    'join-with up',                                       # Another alternative is 'move right' which would limit the other code windows to 1/2 of the screen
]
alt-shift-w = [
    'layout floating',
    'move-node-to-workspace --focus-follows-window web',
    'layout tiling',
    'join-with up',
]
alt-shift-g = [
    'layout floating',
    'move-node-to-workspace --focus-follows-window llm',
    'layout tiling',
    'join-with up',
]
alt-shift-r = [
    'layout floating',
    'move-node-to-workspace --focus-follows-window notes',
    'layout tiling',
    'join-with up',
]
alt-shift-z = [
    'layout floating',
    'move-node-to-workspace --focus-follows-window zoom',
    'layout tiling',
    'join-with up',
]

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
# alt-shift-w = 'join-with left'
# alt-shift-t = 'join-with up'

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-shift-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-shift-a = 'focus parent'


# --------------------------------------------------------------------------
#                                  Modes                                 
# -------------------------------------------------------------------------- 

alt-shift-semicolon = 'mode resize'
alt-shift-period = 'mode layout'
alt-shift-m = 'mode move'
alt-semicolon = 'mode workspaces_extra'

[mode.workspaces_extra.binding]
# Remember to add any new workspaces to window callbacks below
s = ['workspace slack --auto-back-and-forth', 'mode main']
o = ['workspace outlook --auto-back-and-forth', 'mode main']
l = ['workspace spotify --auto-back-and-forth', 'mode main']  # 'listen'
t = ['workspace terminal --auto-back-and-forth', 'mode main']
f = ['workspace files --auto-back-and-forth', 'mode main']    # Excel, Word, PPT

alt-shift-s = ['move-node-to-workspace slack', 'mode main']
alt-shift-o = ['move-node-to-workspace outlook', 'mode main']
alt-shift-l = ['move-node-to-workspace spotify', 'mode main']
alt-shift-t = ['move-node-to-workspace terminal', 'mode main']
alt-shift-f = ['move-node-to-workspace files', 'mode main']

enter = 'mode main'
esc = 'mode main'

[mode.layout.binding]
# alt-shift-s = 'layout v_accordion'               # 'layout stacking' in i3
# alt-shift-w = 'layout h_accordion'               # 'layout tabbed' in i3

t = ['layout tiles accordion', 'mode main']
# 'layout toggle split' in i3
w = ['layout tiles horizontal vertical', 'mode main']
f = "flatten-workspace-tree"
# 'floating toggle' in i3
c = ['layout floating tiling', 'mode main']

enter = 'mode main'
esc = 'mode main'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'

enter = 'mode main'
esc = 'mode main'

[mode.move.binding]
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'
enter = 'mode main'
esc = 'mode main'

# --------------------------------------------------------------------------
#                                  Callbacks                                 
# -------------------------------------------------------------------------- 

# list of popular application IDs: https://nikitabobko.github.io/AeroSpace/goodness#popular-apps-ids
# You can use 'aerospace list-apps' CLI command to get IDs of running applications
# mdls -name kMDItemCFBundleIdentifier -r /Applications/App.app

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = false
run = 'move-node-to-workspace code'

[[on-window-detected]]
# Cursor
if.app-id = 'com.todesktop.230313mzl4w4u92'
check-further-callbacks = false
run = 'move-node-to-workspace code'


[[on-window-detected]]
if.app-id = 'com.google.Chrome'
check-further-callbacks = false
run = 'move-node-to-workspace web'

[[on-window-detected]]
if.app-id = 'md.obsidian'
check-further-callbacks = false
run = 'move-node-to-workspace notes'

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.fmpnliohjhemenmnlpbfagaolkdacoja'
check-further-callbacks = false
run = 'move-node-to-workspace llm'

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.bkoempnccdngdbcdinnemijnjklpmmod'
check-further-callbacks = false
run = 'move-node-to-workspace llm'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
check-further-callbacks = false
run = 'move-node-to-workspace llm'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
check-further-callbacks = false
run = 'move-node-to-workspace outlook'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
check-further-callbacks = false
run = 'move-node-to-workspace spotify'

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
check-further-callbacks = false
run = 'move-node-to-workspace zoom'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
check-further-callbacks = false
run = 'move-node-to-workspace zoom'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
check-further-callbacks = false
run = 'move-node-to-workspace slack'

[[on-window-detected]]
if.app-id = 'org.alacritty'
check-further-callbacks = false
run = 'move-node-to-workspace terminal'
# run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
check-further-callbacks = false
run = 'move-node-to-workspace files'

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
check-further-callbacks = false
run = 'move-node-to-workspace files'

[[on-window-detected]]
if.app-id = 'com.microsoft.Powerpoint'
check-further-callbacks = false
run = 'move-node-to-workspace files'

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
check-further-callbacks = false
run = 'move-node-to-workspace files'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = false
run = ['layout floating', 'move-node-to-workspace files']

[[on-window-detected]]
if.app-id = 'org.eyebeam.SelfControl'
check-further-callbacks = false
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
check-further-callbacks = false
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
check-further-callbacks = false
run = ['layout floating']


# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace 1']
