# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
#enable-normalization-flatten-containers = false
#enable-normalization-opposite-orientation-for-nested-containers = false

start-at-login = true
# The 'accordion-padding' specifies the size of accordion padding
# accordion is the default mode for default workspace 1. Not sure why.
accordion-padding = 0

# I'm not sure why workspace 1 is accordion even though this is the default: 
# default-root-container-layout = 'tiles'

[mode.main.binding]
alt-shift-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

# alt-shift-shift-j = 'move left'
# alt-shift-shift-k = 'move down'
# alt-shift-shift-l = 'move up'
# alt-shift-shift-semicolon = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-shift-w = 'join-with left'
alt-shift-t = 'join-with up'

alt-shift-f = 'fullscreen'

# alt-shift-s = 'layout v_accordion'               # 'layout stacking' in i3
# alt-shift-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-shift-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

# TODO Could make some apps (Finder) float by default maybe: https://nikitabobko.github.io/AeroSpace/guide#dialog-heuristics

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-shift-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-shift-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-shift-r = 'flatten-workspace-tree'

alt-shift-m = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
