approval_policy = "untrusted"
# https://github.com/openai/codex/blob/main/docs/config.md#model_reasoning_effort
model_reasoning_effort = "high" # default is medium
# Output length? not really sure:
model_verbosity = "medium" # default is medium
# Chain of thought summary:
model_reasoning_summary = "auto" # default is auto
# read-only: can read ANY file on disk, but not write file or use network
# workspace-write: can write files in current working directory, but not use network
# danger-full-access: can read/write any file on disk and use network
sandbox_mode = "read-only" # default is read-only


# Setting `profile` is equivalent to specifying `--profile o3` on the command
# line, though the `--profile` flag can still be used to override this value.

[profiles.o3]
model = "o3"
model_provider = "openai"
approval_policy = "never"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
