---

- name: install apcupsd
  package:
    name: apcupsd
    state: present

- name: ensure config has name set correctly
  lineinfile:
    path: /etc/apcupsd/apcupsd.conf
    regexp: "^UPSNAME"
    line: "UPSNAME APC_{{ ansible_hostname }}"

- name: ensure config is configured for USB UPS
  lineinfile:
    path: /etc/apcupsd/apcupsd.conf
    regexp: "^DEVICE /dev/ttys0"
    line: "DEVICE"

- name: enable apcupsd service
  systemd:
    name: apcupsd
    state: restarted
    enabled: true