---

- name: Create config directory
  file:
    path: /etc/sanoid
    state: directory
    mode: "0755"
  become: true

- name: configure sanoid
  copy:
    #src: sanoid/sanoid.conf
    src: "sanoid/{{ sanoid_config_source }}"
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: '0644'