---

- name: sanoid setup
  include_tasks: sanoid.yaml
  tags:
    - sanoid
  when: sanoid_build_from_source

- name: configure sanoid
  include_tasks: configure.yaml
  when: syncoid_configure

# todo remove this hack
- name: ensure sanoid is installed
  apt:
    name: sanoid
    state: present
  ignore_errors: True

- name: replication setup
  include_tasks: replication.yaml
  tags:
    - replication

- name: Give user passwordless access to ZFS commands
  lineinfile:
    path: /etc/sudoers
    line: "{{ main_username }} ALL=(ALL) NOPASSWD: /usr/sbin/zfs,/usr/sbin/zpool"
  become: true