---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - cifs-utils
      - smbclient
    state: present
    update_cache: yes

- name: Create mount point
  ansible.builtin.file:
    path: "{{ samba_client_mount }}"
    state: directory
    mode: "0755"

- name: Add fstab entry for Samba share
  ansible.builtin.mount:
    path: "{{ samba_client_mount }}"
    src: "{{ samba_share_path }}"
    fstype: "cifs"
    opts: "nofail,username={{ samba_share_user }},password={{ samba_share_pw }},iocharset=utf8,uid={{ main_user_uid }},gid={{ main_user_gid }},file_mode=0660,dir_mode=0770"
    state: mounted
    dump: 0
    passno: 0
