---
- name: systemd daemon-reload
  command: systemctl daemon-reload

- name: start samba service
  service:
    name: smbd
    state: started

- name: restart samba service
  service:
    name: smbd
    state: restarted

- name: restart telegraf
  service:
    name: telegraf
    state: restarted

- name: reload docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted