version: "3.3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      default:
    command:
      - "--log.level=debug"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.0.0.1:53"
      #- "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cloudflare.acme.email=123@123.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    environment:
      - CLOUDFLARE_EMAIL=123@123.com
      - CLOUDFLARE_API_KEY=secret
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/mnt/storage/appdata/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  nginx:
    image: linuxserver/nginx
    container_name: my-web-nginx
    depends_on:
        - traefik
    environment:
        - PUID=1000
        - PGID=1000
    restart: unless-stopped
    labels:
        - traefik.enable=true
        - traefik.http.routers.nginx.rule=(Host(`test.domain.com`) && Path(`/nginx`))
        - traefik.http.routers.nginx.entrypoints=websecure
        - traefik.http.routers.nginx.tls.certresolver=cloudflare
  nginx:
    image: linuxserver/nginx
    container_name: my-web-nginx
    depends_on:
        - traefik
    environment:
        - PUID=1000
        - PGID=1000
    restart: unless-stopped
    labels:
        - traefik.enable=true
        - traefik.http.routers.nginx.rule=Host(`test.domain.com`)
        - traefik.http.routers.nginx.entrypoints=websecure
        - traefik.http.routers.nginx.tls.certresolver=cloudflare
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - UMASK_SET=022
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.domain.com`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=cloudflare
