---

- name: Ensure the repository is up-to-date
  hosts: localhost
  tasks:
    - name: Update repository
      ansible.builtin.git:
        repo: 'https://github.com/mjmaurer/stable-diffusion-webui-docker.git'
        dest: "{{ machine_dir }}/stable-diffusion-webui-docker" 
        update: yes