---
- name: ensure destination for autorestic configuration file exists
  file:
    path: "{{ autorestic_generator_output_path }}"
    state: directory

# - name: write autorestic conf file
#   template:
#     backup: yes
#     src: ../templates/autorestic.yml.j2
#     dest: "{{ autorestic_generator_output_path }}/.autorestic.yml"
#     owner: "{{ autorestic_generator_generator_uid }}"
#     group: "{{ autorestic_generator_generator_gid }}"

- name: copy autorestic config file
  copy:
    src: "autorestic/{{ ansible_hostname }}.autorestic.yml"
    dest: "{{ autorestic_generator_output_path }}/.autorestic.yml"
    owner: "{{ autorestic_generator_generator_uid }}"
    group: "{{ autorestic_generator_generator_gid }}"
  when: simple_autorestic_decrypt
