---

- name: ensure lm_sensors is installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - lm_sensors

- name: copy fancontrol configuration to target
  copy:
    src: etc/fancontrol
    dest: /etc/fancontrol

- name: enable fancontrol service
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    name: fancontrol