---

- name: ensure required package deps are present
  ansible.builtin.package:
    name:
      - bash
      - curl
      - findmnt
      - grep
      - awk
      - blkid
      - lsblk
      - nfs-common 
      - open-iscsi
    state: present

  - name: Start and Enable Airflow
    systemd:
      name: open-iscsi
      state: started
      enabled: yes
      daemon-reload: yes