''
  " =============================================================================
  " IdeaVim Configuration - Generated by Nix
  " =============================================================================

  " --------------------------------- Plugins ----------------------------------
  set surround
  set commentary
  set multiple-cursors
  set highlightedyank
  set nerdtree
  set argtextobj
  set exchange

  " Plugin settings
  let g:argtextobj_pairs="[:],(:),<:>"
  let g:highlightedyank_highlight_duration = "150"

  " --------------------------------- Settings ---------------------------------
  let mapleader = " "
  set clipboard+=unnamed
  set clipboard+=ideaput
  set scrolloff=5
  set incsearch
  set hlsearch
  set ignorecase
  set smartcase
  set showmode
  set number
  set ideajoin
  set ideastatusicon=gray

  " ----------------------------- Handler Control --------------------------------
  " Let IDE handle these keys (not IdeaVim)
  sethandler <C-a> a:ide
  sethandler <C-b> a:ide
  sethandler <C-e> a:ide
  sethandler <C-f> a:ide
  sethandler <C-g> a:ide
  sethandler <C-h> a:ide
  sethandler <C-k> a:ide
  sethandler <C-l> a:ide
  sethandler <C-n> a:ide
  sethandler <C-p> a:ide
  sethandler <C-q> a:ide
  sethandler <C-r> a:ide
  sethandler <C-t> a:ide
  sethandler <C-v> a:ide
  sethandler <C-w> a:ide
  " Let IdeaVim handle these
  sethandler <C-d> a:vim
  sethandler <C-u> a:vim
  sethandler <C-o> a:vim
  sethandler <C-i> a:vim

  " ==================== Shared Normal + Visual Mode Mappings ====================

  " Command palette
  map <leader>p <Action>(GotoAction)

  " Recent projects
  map <leader>[ <Action>(ManageRecentProjects)

  " Open folder / project
  map <leader>] <Action>(OpenFile)

  " AI (requires AI Assistant plugin)
  map <leader>aa <Action>(ActivateAIAssistantToolWindow)

  " ---------- Editor prefix (<leader>e) ----------
  " Toggle line comment
  map <leader>ee <Action>(CommentByLineComment)

  " Find and replace
  map <leader>er <Action>(Replace)

  " Rename
  map <leader>en <Action>(RenameElement)

  " Open external docs
  map <leader>el <Action>(ExternalJavaDoc)

  " ---------- Git prefix (<leader>g) ----------
  " Copy remote file URL
  map <leader>gc <Action>(CopyPathFromRepositoryRootProvider)

  " Revert hunk
  map <leader>gr <Action>(Vcs.RollbackChangedLines)

  " ==================== Normal Mode Only Mappings ==============================

  " Definition preview hover
  nmap <leader>d <Action>(QuickImplementations)

  " Switch project window
  nmap <leader>; <Action>(NextProjectWindow)

  " File structure (symbols in file)
  nmap <leader>i <Action>(FileStructurePopup)

  " All symbols in project
  nmap <leader>I <Action>(GotoSymbol)

  " Go to file (quick open)
  nmap <leader>o <Action>(GotoFile)

  " ---------- Window/tab management (<leader>w) ----------
  nmap <leader>ww <Action>(CloseContent)
  nmap <leader>wh <Action>(CloseAllToTheLeft)
  nmap <leader>wl <Action>(CloseAllToTheRight)
  nmap <leader>wo <Action>(CloseAllEditorsButActive)

  " Format document
  nmap <leader>f <Action>(ReformatCode)

  " Collapse all in tool window
  nmap <leader>c <Action>(CollapseAll)

  " Rename
  nmap <leader>r <Action>(RenameElement)

  " ---------- AI prefix (<leader>a) ----------
  nmap <leader>af <Action>(ActivateAIAssistantToolWindow)

  " ---------- Testing prefix (<leader>t) ----------
  nmap <leader>tq <Action>(Stop)
  nmap <leader>tx <Action>(Stop)

  " ---------- Git prefix (<leader>g) ----------
  " Copy commit SHA
  nmap <leader>gs <Action>(Vcs.CopyRevisionNumberAction)

  " Diff line with working copy
  nmap <leader>gbh <Action>(Vcs.ShowDiffWithLocal)
  nmap <leader>gg <Action>(Vcs.ShowDiffWithLocal)

  " Diff line with previous
  nmap <leader>gbb <Action>(Vcs.ShowDiffWithLocal)
  nmap <leader>gd <Action>(Vcs.ShowDiffWithLocal)

  " Navigate changes in diff
  nmap <leader>gh <Action>(Diff.PrevChange)
  nmap <leader>gl <Action>(Diff.NextChange)

  " ---------- Debug prefix (<leader>b) ----------
  nmap <leader>br <Action>(Rerun)
  nmap <leader>bx <Action>(Debugger.RemoveAllBreakpoints)
  nmap <leader>bd <Action>(ActivateDebugToolWindow)
  nmap <leader>bw <Action>(Debugger.AddToWatch)
  nmap <leader>bs <Action>(Debug)
  nmap <leader>bS <Action>(ChooseDebugConfiguration)
  nmap <leader>bf <Action>(XDebugger.Frames)
  nmap <leader>bc <Action>(EditBreakpoint)
  nmap <leader>bb <Action>(ToggleLineBreakpoint)
  nmap <leader>bj <Action>(ForceRunToCursor)

  " ---------- Tab navigation ----------
  nmap H <Action>(PreviousTab)
  nmap L <Action>(NextTab)

  " Recently used editors
  nmap <leader>hh <Action>(RecentFiles)
  nmap <leader>ll <Action>(RecentFiles)

  " ---------- Vertical navigation ----------
  " Next/prev method (semantic fold navigation for Java)
  nmap J <Action>(MethodDown)
  nmap K <Action>(MethodUp)

  " Navigate back/forward
  nmap <leader>jj <Action>(Back)
  nmap <leader>kk <Action>(Forward)

  " Navigation locations (unified in IntelliJ)
  nmap <leader>jv <Action>(Back)
  nmap <leader>kv <Action>(Forward)

  " Recently used editors (global)
  nmap <leader>jf <Action>(RecentFiles)
  nmap <leader>kf <Action>(RecentFiles)

  " Edit locations
  nmap <leader>je <Action>(JumpToLastChange)
  nmap <leader>ke <Action>(JumpToNextChange)

  " Next/prev error
  nmap <leader>jd <Action>(GotoNextError)
  nmap <leader>kd <Action>(GotoPreviousError)

  " Next/prev git change
  nmap <leader>jg <Action>(VcsShowNextChangeMarker)
  nmap <leader>kg <Action>(VcsShowPrevChangeMarker)

  " Next/prev breakpoint (mapped to bookmarks as closest equivalent)
  nmap <leader>jb <Action>(GotoNextBookmark)
  nmap <leader>kb <Action>(GotoPreviousBookmark)

  " ==================== Visual Mode Only Mappings ==============================

  " Trigger code completion
  vmap <leader>s <Action>(CodeCompletion)

  " Paragraph movement
  vmap J }
  vmap K {

  " ==================== Misc ==================================================

  " Clear search highlight on escape
  nnoremap <Esc> :nohlsearch<CR><Esc>
''
