---

- name: ensure hostname is set correctly
  hostname:
    name: "{{ hostname_morpheus }}"

- name: disks
  include: disks.yml
  tags:
    - disks

- name: file-sharing
  include: file-sharing.yml
  tags:
    - file-sharing

- name: telegraf docker fix
  include: telegraf-fix.yaml

- name: override docker service for zfs dependencies
  include: docker-zfs-override.yml
  when: docker_zfs_override

# perhaps a generic 'node' monitoring setup role?
# - name: monitoring
#   include: monitoring.yml
#   tags:
#     - monitoring